//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        public int Id { get; set; }
        public string NumeroCheque { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public int ClienteId { get; set; }
        public int PagoId { get; set; }
    
        public virtual PAGO PAGO { get; set; }
    }
}
